repos:
  - repo: local
    hooks:
      - id: ruff
        name: ruff
        entry: uv run --no-project ruff check src tests
        language: system
        pass_filenames: false
        always_run: true
      - id: ruff-format
        name: ruff-format
        entry: uv run --no-project ruff format --check src tests
        language: system
        pass_filenames: false
        always_run: true
